// User
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_FOLDERS = "SET_FOLDERS";
export const SET_FOLDER_QUERY = "SET_FOLDER_QUERY";
export const ADD_FOLDER = "ADD_FOLDER";
export const EDIT_FOLDER_NAME = "EDIT_FOLDER_NAME";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const ADD_LIST = "ADD_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const SET_GRAPH_TIMEFRAME = "SET_GRAPH_TIMEFRAME";

export const SET_THEME = "SET_THEME";
export const SET_LIST = "SET_LIST";
export const UPDATE_LIST = "UPDATE_LIST";
export const ADD_ITEM = "ADD_ITEM";
export const SET_LIST_ITEM_QUERY = "SET_LIST_ITEM_QUERY";

// Layout
export const SET_SIDEBAR_STATE = "SET_SIDEBAR_STATE";
export const SET_REMOVEBTN_STATE = "SET_REMOVEBTN_STATE";
export const SET_ACTIVESIDE_STATE = "SET_ACTIVESIDE_STATE";

// Game
export const SET_PLAY_STATE = "SET_PLAY_STATE";
export const SET_CURRENT_ITEM = "SET_CURRENT_ITEM";
export const UPDATE_ANSWER_INPUT_TEXT = "UPDATE_ANSWER_INPUT_TEXT";
export const SET_ITEM_COMPLETE_STATE = "SET_ITEM_COMPLETE_STATE";
export const SET_GAME_COMPLETE_STATE = "SET_GAME_COMPLETE_STATE";
export const SET_ATTEMPT_COUNT = "SET_ATTEMPT_COUNT";
export const SET_SUCCESS_COUNT = "SET_SUCCESS_COUNT";
